# Examples used: 
#   https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/
#   https://docs.docker.com/compose/environment-variables/
#   https://stackoverflow.com/a/47907859

version: "3"
services:
 calliope-node1:
    build:
      context: .
      dockerfile: docker-file
    container_name: calliope-node1
    environment:
      - discovery.type=single-node
    volumes:
      - /home/jacksonlindsay/Desktop/config:/usr/share/elasticsearch/config/
      - /home/jacksonlindsay/Desktop/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - /home/jacksonlindsay/Desktop/securityConfig.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
    ports:
      - 9200:9200
      - 9600:9600
    # https://docs.docker.com/compose/compose-file/#restart
    restart: "always"
