# based on https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/
version: '3'
services:
  aeolus-node1:
    image: amazon/opendistro-for-elasticsearch:1.6.0
    container_name: aeolus-node1
    environment:
      - cluster.name=aeolus-cluster
      - node.name=aeolus-node1
      - discovery.seed_hosts=aeolus-node1
      - cluster.initial_master_nodes=aeolus-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms16384m -Xmx16384m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      #- network.host=0.0.0.0 # required if not using the demo Security configuration
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - aeolus-data1:/usr/share/elasticsearch/data
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./node.pem:/usr/share/elasticsearch/config/node.pem
      - ./node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - ./admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml
      - ./roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
      - ./action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - aeolus-net
    restart: "always" # set to restart after a reboot
kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.6.0
    container_name: aeolus-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://aeolus-node1:9200
      ELASTICSEARCH_HOSTS: https://aeolus-node1:9200
    volumes:
      - ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - aeolus-net
    restart: "always" # set to restart after a reboot
volumes:
  aeolus-data1:
  aeolus-data2:

networks:
  aeolus-net:
